In [1]:
import sys
sys.version

'3.5.2 (default, Sep 14 2017, 22:51:06) \n[GCC 5.4.0 20160609]'

In [2]:
# import load_iris from dataset module in sklearn
from sklearn.datasets import load_iris

In [3]:
#save 'bunch' object containing the iris dataset and attributes in a variable
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [4]:
#print iris data set
print (iris.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

# ML Terminology
    
    -each Row is an observation or sample,example,instance,record
    -each Column is a feature or predictor,attribute,independent variable,input,regressor,covariate

In [5]:
#print the names of four features or columns
print (iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
#print integers representing the species of each obs
print (iris.target)
#represents what we are going to predict

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [7]:
#print the encoding scheme for species 0 = setosa 1 = versicolor 2 = virginica
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


-Each value that is being predicted is the response aka target,outcome,label,dependent variable
-classification is supervised learning which the response is categorical its values are in a finite un-ordered set
-regression is a supervised learning which response is ordered and continuous example(price of house)

must first decide how data is encoded then figure out if classification or regression tech is right


# First step in ML
-get comp to learn relationship between features and response
must be in form sklearn expects in 4 different ways
1) passed in ML model as seperate objects
2) sklearn only expects to see numbers in features and response target, should always be numberic in reg or class
3) expects to be stored as numpy arrays
4) Feaeture and response obj should be certain shapes 2D

numpy has shape attribute to verify the shape of data
response obj expected to have single dimension and should have same mag as feature obj. One response to each attribute

In [8]:
print(iris.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [9]:
print (iris.target.shape)

(150,)


In [10]:
print (iris.data.shape)

(150, 4)


In [11]:
X = iris.data
#uppercase X represent a matrix
y = iris.target
#lowercase y represent a label

# Training a ML model

- Bc the response is categorical this is a categorical question(for IRIS dataset)
- KNN is the K-nearest neighbor a comparitive training model or context clues. Takes n-values nearest to the UNKNOWN data and uses the most popular response as the predictive basis
1) First pick a value for K

In [12]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


When inputing data make sure to meet all 4 key reqs

# Sklearn 4 step modeling pattern


* Step 1 import class you plan to use from sklearn
from sklearn.neighbors import KNeighborsClassifier

In [13]:
from sklearn.neighbors import KNeighborsClassifier

* Step 2 "Instantiate" the "estimator"
-estimator is sklearn model
- this process is instantiation or "make an instance of"

In [14]:
knn = KNeighborsClassifier(n_neighbors=1)
#this is an instance, now have an object knn that knows how to do KNN

3 notes
doesnt matter name of instantiator
specify the argument(n_neighbors) to tell knn object
all parameters not specified are in default

In [15]:
print (knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


* Step 3 "Fit Model with data"
model learns relation btwn x and y
happens in place

In [16]:
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

* Step 4 predict the response
-New obs are called "out of sample" data
- uses info it learned during model training process to predict an outcome

In [17]:
import numpy as np
X_new = [[3, 5, 4, 2]]
#needed to reshape from 1D array to a 2D array. (1,-1) tells 
#Numpy to infer the dimensions to be 1 for the first dimension and then 4 for the second
knn.predict(X_new)

array([2])

- predict method does have a response object in the form of array
- ML doesn't know what array[2] is and therefore is up to us to recall that array 2 is Virginica

In [18]:
X_newer = [[3,4,5,2], [5,4,3,2]]
knn.predict(X_newer)

array([2, 1])

# Using a different Value for K

In [19]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X,y)
knn.predict(X_newer)

array([1, 1])

Sklearn models have uniform interface and can still use the same 4 steps

In [20]:
#import class LogisticsRegression
from sklearn.linear_model import LogisticRegression

#instantiate the model
loreg = LogisticRegression()

#fit the data to the model
loreg.fit(X,y)

#make a prediction
loreg.predict(X_newer)

array([2, 0])

These are out of sample measurment and therefore do not know true response value and would not know which MODEL,KNN or LogisticRegression worked best.
- With Supervised learning want to build models that generalize to new data
-Compare models to existing label data to choose which model is best

# Determining Best Model

Model Eval Procedure
1)Train and Test
The most basic and no brainer training is to have a given dataset with KNOWN values, split it up RANDOMLY into two datasets(train and test) and use each split dataset for their respective names.
This is to troubleshoot if the model is accurate when given outside attributes

In [30]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model
import pandas as pd
irisdf_x = pd.DataFrame(iris.data, columns=iris.feature_names)
irisdf_y = pd.DataFrame(iris.target)

In [28]:
irisdf_x.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.054000           3.758667   
std             0.828066          0.433594           1.764420   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.198667  
std            0.763161  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [29]:
irisdf_y.describe()

0
count  150.000000
mean     1.000000
std      0.819232
min      0.000000
25%      0.000000
50%      1.000000
75%      2.000000
max      2.000000

In [31]:
reg = linear_model.LinearRegression()
xtrain, xtest, ytrain, ytest = train_test_split(irisdf_x, irisdf_y, test_size = .33, random_state = 25)

In [32]:
reg.fit(xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [33]:
reg.coef_

array([[-0.09174738, -0.0790642 ,  0.21665035,  0.61522928]])

In [37]:
a = reg.predict(xtest)
a[2]

array([ 1.58712069])

In [38]:
ytest

0
28   0
72   1
70   1
85   1
128  2
65   1
127  2
42   0
81   1
93   1
21   0
31   0
26   0
133  2
6    0
58   1
125  2
139  2
64   1
94   1
79   1
99   1
66   1
20   0
34   0
117  2
69   1
122  2
120  2
41   0
54   1
113  2
135  2
4    0
115  2
52   1
68   1
40   0
23   0
35   0
16   0
0    0
8    0
25   0
138  2
10   0
33   0
78   1
27   0
121  2

In [39]:
reg.score(xtest,ytest)

0.92325979792510826

Probably best to use another testing model